# Custom Language File for Launcher Customizer

[ejs.app]
title = "Draco Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/MaitreCapybaraoff/DracoLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@DracoMC_off"
mediaDiscordURL = "discord.draco-smp.ovh"

[ejs.settings]
sourceGithubLink = "https://github.com/MaitreCapybaraoff/DracoLauncher"
supportLink = "https://github.com/MaitreCapybaraoff/DracoLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR DRACO SMP"
welcomeDescription = ""
welcomeDescCTA = "Vous êtes à quelques clics du Draco SMP."
